export const EN_NAMES = [
  "Serious Peacocks",
  "Steel Cubs",
  "Golden Mustangs",
  "Dynasty Serpents",
  "Ancient Leopards",
  "Flying Beavers",
  "Quiet Sirens",
  "Golden Cobras",
  "Colossal Skywalkers",
  "Fiery Captains",
  "Supreme Krakens",
  "Wise Minutemen",
  "Abandoned Wizards",
  "Hurricane Gnomes",
  "Odd Lords",
  "Monstrous Comets",
  "Eager Riders",
  "Brutal Energy",
  "Psychodelic Stallions",
  "Ancient Doves",
];
export const UA_NAMES = [
  "Династія чихуахуа",
  "Божевільні горизонти",
  "Справжні патріоти",
  "Дивні мули",
  "Цукрова загроза",
  "Всі альпіністи",
  "Вищий клатч",
  "Шалений бліц",
  "Дослідники кошика",
  "Спокійні лисиці",
  "Ведмеді-скелети",
  "Дитячі комети",
  "Локо дияволи",
  "Урочисті бабуїни",
  "Тузи скелетів",
  "Відомі мули",
  "Веселі матадори",
  "Сталеві комети",
  "Жахливі моряки",
];
